Vagrant.configure("2") do |config|

   	# Specify the base box
   	config.vm.box = "ubuntu/xenial64"

   	# Setup port forwarding
   	config.vm.network :forwarded_port, guest: 80, host: 80, auto_correct: true

       # Setup synced folder
       config.vm.synced_folder "./", "/var/www", create: true, group: "www-data", owner: "www-data"

       # VM specific configs
       config.vm.provider "virtualbox" do |v|
       	v.name = "Vagrant Box"
       	v.customize ["modifyvm", :id, "--cpus", "2"]
       	v.customize ["modifyvm", :id, "--memory", "3048"]
       end
   end